server:
  port: 81
dubbo:
  application:
    name: web-manager
  registry:
    address: zookeeper://192.168.5.130:2181
  consumer:
    # \u9996\u6B21\u542F\u52A8\u4E0D\u68C0\u67E5\u63D0\u4F9B\u8005\u662F\u5426\u5B58\u5728
    check: false
  protocol:
    port: -1
spring:
  thymeleaf:
    cache: false