dubbo:
  application:
    name: cls-service
  registry:
    address: zookeeper://192.168.5.130:2181
spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver