dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://192.168.5.130:2181
  protocol:
    # \u9ED8\u8BA420880\uFF0C\u627E\u4E00\u4E2A\u6CA1\u6709\u88AB\u5360\u7528\u7684\u7AEF\u53E3\u3001
    # \u81EA\u52A8\u53BB\u627E\u4E00\u4E2A\u53EF\u7528\u7684\u7AEF\u53E3
    port: -1
  consumer:
    # \u9996\u6B21\u542F\u7528\u4E0D\u68C0\u67E5\u63D0\u4F9B\u8005\u662F\u5426\u5B58\u5728
    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver